#!/bin/sh
#
# assemble the sources
#

# settings
APOUT=/tmp/apout2.3alpha2/apout
APOUT_ROOT=/tmp/s2
COLD=1

export APOUT_ROOT

tools/rebuild

# fix "mount" issue which 1ed as cant deal with
# and also fix up the vector table in u0.s since
# the result is a slightly different format a.out that doesnt
# include the header in the text segment
test -d build || mkdir build
for f in rebuilt/u?.s ; do
    b=`basename $f`
    if [ $COLD = 1 ] ; then
        sed -e 's/.*init by copy.*/4;4;unkni;0;fpsym;0/' \
	    -e 'sX\[systm-inode\]\\/2X-191.X' \
            -e 's/^mount:/_mount:/' \
            -e 's/$mount/$_mount/' \
            -e 's/cold = 0/cold = 1/' \
	    < $f > build/$b
    else 
        sed -e 's/.*init by copy.*/4;4;unkni;0;fpsym;0/' \
	    -e 'sX[systm-inode]\/2X-101.X' \
            -e 's/^mount:/xmount:/' \
            -e 's/$mount/$xmount/' \
            < $f > build/$b
    fi
done

cd build
$APOUT $APOUT_ROOT/bin/as ../sys1.s u?.s
$APOUT $APOUT_ROOT/bin/nm a.out |sort > a.out.syms
../tools/ml

