#!/bin/sh
#
# assemble the sources
#
if [ ! -d tools ]
then echo 'No tools/ directory, are you running this in the correct dir?'
     exit 1
fi

# settings;  should contain something like:
#   APOUT=/tmp/apout2.3alpha2/apout
#   APOUT_ROOT=/tmp/v7
. tools/assemv7.cfg

export APOUT_ROOT

# build sources from pages and generate patched sources in "build"
# if "cold" is passed in, the "cold" option will be patched on.
tools/rebuild "$@"

# assemble the kernel from patched sources and generate symbols
# and build a simh loadable file.
cd build
$APOUT $APOUT_ROOT/bin/as ../sys1.s u?.s
$APOUT $APOUT_ROOT/bin/nm a.out |sort > a.out.syms
../tools/ml

